const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const formatCurrency = (amount) =>
  `₹${Number(amount).toLocaleString("en-IN")}`;

exports.generatePDF = (reportType, reportData) => {
  return new Promise((resolve, reject) => {
    const reportsDir = path.join(__dirname, "../reports");

    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir);
    }

    const fileName = `${reportType.replace(/\s+/g, "_")}_${Date.now()}.pdf`;
    const filePath = path.join(reportsDir, fileName);

    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Header
    doc
      .fontSize(18)
      .text("TaxPal — Financial Report", { align: "center" })
      .moveDown(0.5);

    doc
      .fontSize(14)
      .text(reportType, { align: "center", underline: true })
      .moveDown(1);

    doc
      .fontSize(10)
      .text(`Generated on: ${new Date().toLocaleDateString()}`)
      .moveDown(1);

    // Table header
    doc.fontSize(12).text("Category", 80).text("Amount", 400);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    let total = 0;

    Object.entries(reportData).forEach(([category, amount]) => {
      total += amount;
      doc
        .moveDown(0.5)
        .text(category, 80)
        .text(formatCurrency(amount), 400);
    });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    // Total
    doc
      .moveDown(0.5)
      .fontSize(12)
      .text("Total", 80)
      .text(formatCurrency(total), 400);

    // Footer
    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("gray")
      .text("Generated by TaxPal", { align: "center" });

    doc.end();

    stream.on("finish", () => resolve(fileName));
    stream.on("error", reject);
  });
};
