// models/User.js
// defines schema for db collections, with basic validations

const { mongoose } = require("../utils/db")

// const mongoose = require("mongoose")

const userSchema = new mongoose.Schema({
    //_id autogenerated by mongoDB
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    country: { type: String, required: true },
    income_bracket: {  //optional field
      type: String,
      enum: ["Low", "Middle", "High"]
    }

    ,isEmailVerified: {
      type: Boolean,
      default: false
    },
    loginOtpHash: {
      type: String
    },
    loginOtpExpire: {
      type: Date
    }

    //new added
    ,resetPasswordToken: {
      type: String
    },
    resetPasswordExpire: {
      type: Date
    }
    
  }, { timestamps: true }
)

module.exports = mongoose.model("User", userSchema)